/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "VehSize"
 * 	found in "VehSize.asn"
 * 	`asn1c -S /home/user/work/normal/asnic/asn1c-0.9.28/skeletons -gen-PER -pdu=auto`
 */

#ifndef	_VehicleHeight_H_
#define	_VehicleHeight_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleHeight */
typedef long	 VehicleHeight_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleHeight;
asn_struct_free_f VehicleHeight_free;
asn_struct_print_f VehicleHeight_print;
asn_constr_check_f VehicleHeight_constraint;
ber_type_decoder_f VehicleHeight_decode_ber;
der_type_encoder_f VehicleHeight_encode_der;
xer_type_decoder_f VehicleHeight_decode_xer;
xer_type_encoder_f VehicleHeight_encode_xer;
per_type_decoder_f VehicleHeight_decode_uper;
per_type_encoder_f VehicleHeight_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleHeight_H_ */
#include <asn_internal.h>
